version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd ./.circleci; ./setup-imagemagick.sh
      - run: npm install
      - run: npm run lint
      - run: npm run cov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - test:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
